/**
 * Daemon Worker — 无头 Agent 执行器
 * ADR-030 / RFC-006 / S8-T08
 */

import type { GitHubPREvent, WorkerResult, DaemonConfig } from "./types.ts";
import { GitCloneWorkspaceProvider } from "./workspace.ts";
import { FileStorageAdapter } from "./storage.ts";

export class DaemonWorker {
  private config: DaemonConfig;
  private storage: FileStorageAdapter;
  private running = 0;

  constructor(config: DaemonConfig) {
    this.config = config;
    this.storage = new FileStorageAdapter(config.storage_path ?? "/tmp/sid-code-daemon/sessions");
  }

  canAccept(): boolean {
    return this.running < this.config.max_concurrent;
  }

  async handlePR(event: GitHubPREvent): Promise<WorkerResult> {
    const eventId = `pr-${event.owner}-${event.repo}-${event.number}-${Date.now()}`;
    const start = Date.now();
    this.running++;

    const workspace = new GitCloneWorkspaceProvider(this.config.workspace_base);

    try {
      await workspace.prepare({
        repo: `${event.owner}/${event.repo}`,
        branch: event.branch,
        commit: event.commit_sha,
      });

      const workdir = workspace.getWorkdir();

      // 生成 diff（base_branch...branch）
      const { execSync } = await import("node:child_process");
      let diff: string;
      try {
        execSync(`git fetch origin ${event.base_branch} --depth 1`, {
          cwd: workdir,
          stdio: "pipe",
          timeout: 30_000,
        });
        diff = execSync(`git diff origin/${event.base_branch}...HEAD`, {
          cwd: workdir,
          encoding: "utf-8",
          timeout: 30_000,
        });
      } catch {
        diff = execSync("git diff HEAD~1", {
          cwd: workdir,
          encoding: "utf-8",
          timeout: 30_000,
        });
      }

      // 调用 code-review Skill（简化版：直接调 scripts）
      const output = await this.runCodeReview(diff, workdir);

      await this.storage.saveSession(eventId, {
        event,
        output,
        completed_at: Date.now(),
      });

      return {
        event_id: eventId,
        skill: "code-review",
        status: "success",
        output,
        duration_ms: Date.now() - start,
      };
    } catch (err) {
      return {
        event_id: eventId,
        skill: "code-review",
        status: "error",
        duration_ms: Date.now() - start,
        error: err instanceof Error ? err.message : String(err),
      };
    } finally {
      await workspace.cleanup();
      this.running--;
    }
  }

  private async runCodeReview(diff: string, _workdir: string): Promise<string> {
    // MVP: 返回 diff 摘要 + 触发 Skill 的占位
    // 真实实现需要调用 sid-code 主循环（headless mode）
    const lines = diff.split("\n");
    const files = lines.filter((l) => l.startsWith("+++ b/")).map((l) => l.slice(6));
    const additions = lines.filter((l) => l.startsWith("+") && !l.startsWith("+++")).length;
    const deletions = lines.filter((l) => l.startsWith("-") && !l.startsWith("---")).length;

    return [
      "## Code Review Report (Daemon MVP)",
      "",
      `**Files Changed**: ${files.length}`,
      `**Additions**: ${additions}`,
      `**Deletions**: ${deletions}`,
      "",
      "### Files",
      ...files.slice(0, 30).map((f) => `- ${f}`),
      files.length > 30 ? `- ... and ${files.length - 30} more` : "",
      "",
      "---",
      "*Generated by sid-code Daemon MVP (RFC-006)*",
    ].join("\n");
  }
}
